service: demo
org: seanhess
app: my-first-app

provider:
  name: aws
  runtime: haskell

functions:
  value:
    handler: server.value

  hello:
    handler: server.hello
    events:
      - http:
          path: hello/{name}
          method: get

    # Here, mypackage is the Haskell package name and myfunc is the executable
    # name as defined in the Cabal file. The handler field may be prefixed
    # with a path of the form `dir1/.../dirn`, relative to `serverless.yml`,
    # which points to the location where the Haskell package `mypackage` is
    # defined. This prefix is not needed when the Stack project is defined at
    # the same level as `serverless.yml`.

plugins:
  - serverless-haskell
  - serverless-offline
